modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ItemFrament/issues"
license="MIT"

[[mods]]
modId="itemframent"
version="${file.jarVersion}"
displayName="Item framen't"
displayURL="https://www.curseforge.com/minecraft/mc-mods/item-frament"
authors="Mrbysco, ShyNieke"
description='''
What item frames?
'''

[[dependencies.itemframent]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.6.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="itemframent.mixins.json"