modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/ItemFrament/issues"
license="MIT"

[[mods]]
modId="itemframent"
version="${file.jarVersion}"
displayName="Item framen't"
displayURL="https://www.curseforge.com/minecraft/mc-mods/item-frament"
authors="Mrbysco, ShyNieke"
description='''
What item frames?
'''

[[dependencies.itemframent]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "itemframent.mixins.json"